spring.application.name=paper

backblaze.endpoint=s3.us-west-004.backblazeb2.com
backblaze.region=us-west-004
backblaze.bucket-name=paper-service
backblaze.access-key=00403bd09649aa90000000001
backblaze.secret-key=K004070AhjBEGzjps8C/aaDLmSfF47A